name: Specter
version: 0.7
author: Falkirks
main: specter\Specter
api: [3.11]
depend: ["iControlU"]
commands:
  specter:
    usage: /specter <action> <player> [params]
    permission: specter.command
    aliases: ['s']
permissions:
  specter:
    default: op
    children:
      specter.command:
        default: op
